# Generated by Django 4.1.7 on 2023-03-31 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Договор купли-продажи'), (2, 'Договор энергоснабжения')], null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('number', models.IntegerField(unique=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('acpoint', models.CharField(max_length=255, null=True)),
                ('mrate', models.CharField(max_length=255, null=True)),
                ('main_voltage', models.CharField(max_length=255, null=True)),
                ('calc_scheme', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Сounterparty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('inn', models.CharField(blank=True, max_length=200, null=True)),
                ('kpp', models.CharField(blank=True, max_length=200, null=True)),
                ('okpo', models.CharField(blank=True, max_length=200, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=200, null=True)),
                ('okved', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=200, null=True)),
                ('Contract', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Tu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField(blank=True, default=None)),
                ('calc_type', models.IntegerField(blank=True, choices=[(1, 'По показаниям'), (2, 'Процент от головы'), (3, 'С вычетом из головы'), (4, 'Процент от головы')], null=True)),
                ('addr', models.CharField(blank=True, default=True, max_length=255)),
                ('Contract', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contract')),
                ('Сounterparty', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='main.сounterparty')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='rate',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='main.rate'),
        ),
    ]
