# Generated by Django 4.1.7 on 2023-04-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, default=None)),
                ('desc', models.CharField(blank=True, default=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='mResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mChannel', models.IntegerField(blank=True, default=None)),
                ('srart', models.IntegerField(blank=True, default=None)),
                ('end', models.IntegerField(blank=True, default=None)),
                ('valeu', models.IntegerField(blank=True, default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='сounterparty',
            name='group',
        ),
        migrations.RemoveField(
            model_name='сounterparty',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='сounterparty',
            name='ogrn',
        ),
        migrations.RemoveField(
            model_name='сounterparty',
            name='okpo',
        ),
        migrations.RemoveField(
            model_name='сounterparty',
            name='okved',
        ),
    ]
