# Generated by Django 4.1.1 on 2023-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mchannel_mresults_remove_сounterparty_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tu',
            name='ats_code',
            field=models.IntegerField(max_length=16, null=True),
        ),
    ]
