# Generated by Django 4.1.7 on 2023-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='ats_code',
            field=models.IntegerField(null=True),
        ),
    ]
