# Generated by Django 4.1.7 on 2023-05-30 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tu_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tu',
            name='addr',
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tu',
            name='code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tu',
            name='Сounterparty',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.сounterparty'),
        ),
    ]
