# Generated by Django 4.1.7 on 2023-05-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tu_addr_alter_tu_code_alter_tu_сounterparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measuring_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_code', models.IntegerField(max_length=16, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('power_object_name', models.CharField(max_length=255, null=True)),
                ('connection_name', models.CharField(max_length=255, null=True)),
                ('location_description', models.CharField(max_length=255, null=True)),
                ('tu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tu')),
            ],
        ),
    ]
