# Generated by Django 4.1.7 on 2023-06-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_measuring_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measuring_channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_code', models.IntegerField(max_length=2, null=True)),
                ('Measuring_point_code', models.IntegerField(max_length=16, null=True)),
                ('full_code', models.CharField(max_length=25, null=True)),
                ('period', models.IntegerField(choices=[(30, '30'), (60, '60')], default=30)),
                ('Measuring_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measuring_point')),
            ],
        ),
    ]
