# Generated by Django 4.1.7 on 2023-06-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_measuring_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measuring_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Measuring_point_code', models.IntegerField(max_length=16, null=True)),
                ('channel_ats_code', models.IntegerField(max_length=2, null=True)),
                ('period_start', models.IntegerField(max_length=4, null=True)),
                ('period_end', models.IntegerField(max_length=4, null=True)),
                ('value', models.IntegerField(max_length=10, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Активный прием'), (2, 'Активная отдача'), (3, 'Реактивный прием'), (4, 'Реактивная отдача')], null=True)),
                ('Measuring_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measuring_channel')),
                ('Measuring_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measuring_point')),
            ],
        ),
    ]
