# Generated by Django 4.1.7 on 2023-06-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_measuring_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuring_data',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
